Class Supplier has been added
infoshareacademy/jpydzr6-potato-code-studio pull request #21
Opened 2024-11-14 21:08 UTC by Wojciech-Wawrzyszko

Class Suppliers is a subclass of Class User.

2024-11-15 10:19 UTC, JakubCharkiewicz requested changes

2024-11-15 10:19 UTC, JakubCharkiewicz commented on supplier.py
> +#     s1.save_categories_to_file()
Gdy dodaję dane dostawcy metodą: add_supplier_details() a później printuję to w outpucie dostaję następującą linijkę:
{'Basia Basiowska': {'first_name': 'Basia', 'last_name': 'Basiowska'}, 'Sikorskiego, <EMAIL>, 566233452': {'customer_address': 'Sikorskiego', 'email': '<EMAIL>', 'telephone': '566233452'}}. Zwróć uwagę na customer_adress. Wydaję mi się, że nie przy dostawcy nie powinniśmy móc podawać adresu klienta. Co więcej, gdy korzystam z metody get_suppliers() dostaję ten sam output co powyżej.  Można jeszcze dodać dunder metody str oraz repr.

2024-11-15 17:42 UTC, Wojciech-Wawrzyszko commented
Klasa Supplier nie dziedziczy już po klasie User (posiada własne nazwy argumentów).

2024-11-16 13:57 UTC, JakubCharkiewicz approved these changes

2024-11-25 14:40 UTC, merged