Add payment method
infoshareacademy/jpydzr6-potato-code-studio pull request #39
Opened 2024-12-06 20:44 UTC by PawelEnerlich

2024-12-06 21:20 UTC, mkusztal commented
`Wybierz działanie:

[1] Wyświetl produkty
[2] Pokaż koszyk
[3] Usuń produkt z koszuka
[4] Mini Quiz o tematyce BIO
[5] Dodaj produkt do magazynu
[6] Sortuj produkty
[7] Przejdź do płatności
[Q] Wyjście z programu

    2
Twój koszyk jest pusty
Czy chcesz przejść do płatności? tak / nie: tak
Twój koszyk jest pusty
Twój koszyk jest warty: 0 PLN
[1] Przejście do zapłaty
[2] Powrót do menu
Twój wybór: 1
Czy na pewno chcesz zapłacić tak / nie ?tak
Brawo właśnie kupiłeś u nas produkt.
Twój koszyk został opróżniony.`

Wydaje mi się że w momencie gdy koszyk jest pusty nie powinniśmy mieć możliwości, aby kontynuować płatność.

2024-12-06 21:38 UTC, mkusztal requested changes
Sprawdź komentarze

2024-12-06 21:38 UTC, mkusztal commented on menu.py
> +                while True:
Może wrzucilibyś to do osobnej funckji i wywołał ją pod `cart.show_cart()`

2024-12-06 21:38 UTC, mkusztal commented on payment.py
> +                while True:
Może wrzucilibyś to do osobnej funckji i wywołał ją pod `case "1":`

2024-12-06 21:38 UTC, mkusztal commented on menu.py
> +                while True:
Czy potrzebujemy 2 razy przechodzić do płatności?

2024-12-06 21:38 UTC, mkusztal commented on payment.py
> +                                cart_instance.basket.clear()
A co z funkcją  `make_basket_empty()`?

2024-12-06 22:20 UTC, JakubCharkiewicz commented
+ w tej metodzie przy potwierdzeniu zakupu mieliśmy poprosić usera o maila :)

2024-12-09 19:18 UTC, PawelEnerlich commented
Branch #39 has been updated.

2024-12-09 21:14 UTC, mkusztal requested changes
Błędy nie zostały poprawione.

2024-12-10 01:34 UTC, mkusztal approved these changes

2024-12-10 15:32 UTC, merged